# encoding: utf-8
# vim: ft=ruby expandtab shiftwidth=2 tabstop=2

#
# General Settings
#
wp_box: vccw-team/xenial64

#
# Virtual Machine Settings
#
memory: 512
cpus: 1

#
# Network Settings
#
hostname: vccw.dev
hostname_old: vccw.old.dev
ip: 192.168.33.10
sync_folder: 'www/wordpress'
sync_folder_guest: '/var/www/wordpress'

#
# WordPress Settings
#
version: latest
lang: en_US
title: Welcome to the VCCW
multisite: false
rewrite_structure: /archives/%post_id%

#
# WordPress Path
#
document_root: '' # Path to document-root relative to sync_folder_guest
wp_siteurl: ''    # Path to the WP_SITEURL like "wp"
wp_home: ''       # Path to the WP_HOME like "wp"

#
# WordPress User
#
admin_user: admin
admin_pass: admin
admin_email: vccw@example.com

#
# WordPress Database
#
db_prefix: wp_
db_host: localhost
db_name: wordpress
db_user: wordpress
db_pass: wordpress

#
# WordPress Default Plugins
# Plugin's slug or url to the plugin's slug.
#
plugins: []

#
# WordPress Default Theme
# Theme's slug or url to the theme's .zip.
#
theme: ''

#
# WordPress Options
#
options:
  blogdescription: Hello VCCW.

#
# The values of wp-config.php
#
force_ssl_admin: false
wp_debug: true
savequeries: false

#
# Theme unit testing
#
theme_unit_test: false
theme_unit_test_uri: https://wpcom-themes.svn.automattic.com/demo/theme-unit-test-data.xml
# theme_unit_test_uri: https://raw.githubusercontent.com/jawordpressorg/theme-test-data-ja/master/wordpress-theme-test-date-ja.xml

#
# DB will be reset when provision
#
reset_db_on_provision: true

#
# Linked Clone for Vagrant v1.8
#
linked_clone: false

#
# RubyGems
#
# ruby_gems:
#   - serverspec

#
# NPM modules
#
# npms:
#   - grunt-cli

#
# composer
#
# composers:
#   - phpmd/phpmd:*
#   - sebastian/phpcpd:*
#   - phploc/phploc:*
#   - phing/phing:*

#
# wp-cli package commands
#
# wp_cli_packages:
#   - shifter/cli:@stable


#
# DB import
#
import_sql: false
import_sql_file: db.sql

#
# WXR import
#
import_wxr: false
import_wxr_file: db.xml

# Misc.
overwrite_htaccess: true # Set false if you want to preserve existing .htaccess in your project
